[description]
== Description

****
ChecklistBank is a platform that supports the publication, analysis, and curation of checklists with emphasis in taxonomic and nomenclatural data. It is an integral part of the infrastructure developed and maintained by the Catalogue of Life (COL) and the Global Biodiversity Information Facility (GBIF).

ChecklistBank includes all https://www.catalogueoflife.org/data/source-datasets[checklists] that form the Catalogue of Life, which are primarily global species lists provided by specific taxonomic communities. However, there are many other sources and uses for taxonomic checklists, such as national or local species lists, lists that share a common attribute such as red lists or invasive species lists, or lists that summarise taxonomic publications. Through ChecklistBank, we facilitate the discovery, use and citation of these valuable resources.

ChecklistBank is provided as a fundamental tool to ensure that basic data on species names and classifications can be shared and reused in support of the biological sciences and wider societal uses.
 
Currently, ChecklistBank provides a repository and a suite of tools to explore its content, and further examine checklists of particular interest. In this tutorial, we provide 4 exercises to explore these tools:

1. Explore the *ChecklistBank repository*: search, inspect and download checklists.
2. *Cross dataset search* tool: look up the appearance of a particular scientific name in all data sources available in ChecklistBank.
3. *Name match* tool: enables comparison of the COL Checklist with one or two other datasets in ChecklistBank in terms of taxon name matching.
4. *Dataset comparison* tool: allows for comparison of two taxonomic datasets in ChecklistBank on a scientific name by scientific name basis.

****

=== Audience
This tutorial is for anyone interested in discovering, curating and publishing checklists with emphasis in taxonomic and nomenclatural checklists.

