[glossary]
== Glossary

//Glossaries are optional. Glossaries entries are an example of a style of AsciiDoc labelled lists.

[glossary]
[[API]]API:: Application Programming Interface.  
A set of clearly defined methods of communication between various software components.

[[CC]]CC Licences:: Creative Commons. 
These are a series of licenses set up by the Creative Commons organization that enable sharing and reuse of creativity and knowledge through the provision of free legal tools.

[[COL]]COL:: Catalogue of Life.
A global collaboration bringing together the effort and contributions of taxonomists and informaticians from around the world.

[[vocab]]Controlled Vocabulary:: This is a restricted set of terms that are used as possible values for a given field. 
One can think of it as a lookup list or dropdown for a particular field. 
For example the DwC field basisOfRecord should only contain one of these values: "PreservedSpecimen", "FossilSpecimen", "LivingSpecimen", "HumanObservation", "MachineObservation". 
We would say that list of values is a controlled vocabulary for that field.

[[DOI]]DOI:: Digital Object Identifier. 
A persistent identifier or handle used to uniquely identify objects. DOIs are in wide use mainly to identify academic, professional, and government information, such as journal articles, research reports and data sets, and official publications.

[[DwC]]DwC:: Darwin Core is a biodiversity data standard, maintained by TDWG & widely used within the GBIF community and partners. 
It is a set of standardized terms (or field names) and their definitions, which are used to share biodiversity information.

[[DwC-A]]DwC-A:: Darwin Core Archive. 
A compressed (zipped) file containing all the information needed to share with GBIF, for a particular resource. 
Each zip contains three types of files:
. the actual data, in one or more text files: occurrence.txt/event.txt/measurmentoffact.txt etc 
. a mapping file: rtf.xml
. a metadata (EML) file: eml.xml
When you publish using the IPT, it creates a Darwin Core Archive, which is shared with GBIF. 
Also, when you download data from the GBIF website you can choose a DwC-A format as well.

[[GUID]]GUID:: Globally Unique IDentifier


<<<
